project_id           = "teamcity-windows-poc"
password             = "StrongNewP@ss123" 
region               = "us-central1"
zone                 = "us-central1-a"
service_account_email = "gha-runner-sa@teamcity-windows-poc.iam.gserviceaccount.com"
