variable "project_id" {}
variable "region" {}
variable "zone" {}
variable "instance_name" {}
variable "machine_type" {}
variable "image" {}
variable "network" {}
variable "subnet" {}
variable "service_account" {}
variable "gcs_bucket" {}
